name: day_1
description: Day 1 solution of AOC 2022.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
   args: 2.3.1
   equatable: 2.0.5
   path: ^1.8.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
