name: aoc
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5
  equations: ^4.1.0
  mocktail: ^0.3.0
  quiver: ^3.1.0
  stack: ^0.2.1
  tuple: ^2.0.1

dev_dependencies:
  test: ^1.22.1
